### ISSUE TITLE
Arrows of orientation

### ISSUE THREAD

**Issue by dbvis-eren-ck** [dbvis-eren-ck/collective-movement-exploration#10]
Arrows of orientation for each individual animal and the centroid

**Comment by joljols** [comment]
You can find details how to calculate the relative positions of the fish and to the centroid of the group in our paper here: http://www.biorxiv.org/content/early/2017/04/27/131094. Arrows can then be drawn with the length based on the displacement (with a multiplier) and orientation based on the differentiation between subsequent frames.

**Comment by dbvis-eren-ck** [comment]
Started  in the commit 16963ef

**Comment by dbvis-eren-ck** [comment]
Closed with 9404716
