### ISSUE TITLE
Polarisation

### ISSUE THREAD

**Issue by dbvis-eren-ck** [dbvis-eren-ck/collective-movement-exploration#9]
Calculate polarisation

**Comment by joljols** [comment]
<img width="1029" alt="screen shot 2017-06-28 at 16 16 55" src="https://user-images.githubusercontent.com/8775649/27641807-40bec204-5c1d-11e7-99fd-d769aa7a2ebc.png">
<img width="554" alt="screen shot 2017-06-28 at 16 16 39" src="https://user-images.githubusercontent.com/8775649/27641806-40b8fa40-5c1d-11e7-9da4-daf36bd4bc90.png">
Here is a a way to calculate polarisation
